name: AI Grammar Review

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'docs/**/*.mdx'
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  checks: write
  issues: write

jobs:
  grammar-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run grammar review on Markdown files
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/grammar_review.py

      - name: Generate rdjsonl
        run: python .github/scripts/generate_rdjsonl.py

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run reviewdog suggester
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f suggestions.rdjsonl ]; then
            reviewdog -f=rdjsonl \
              -name="Grammar reviewer" \
              -reporter=github-pr-review \
              -tee -filter-mode=nofilter < suggestions.rdjsonl
          else
            echo "No suggestions.rdjsonl file found, skipping reviewdog."
          fi
