name: AI Grammar Review

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'docs/**/*.mdx'
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  grammar-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run grammar review on Markdown files
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/grammar_review.py

      - name: Generate diff
        run: python .github/scripts/generate_diff.py

      - name: Download reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s

      - name: Run reviewdog suggester
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f suggestions.diff ]; then
            ./bin/reviewdog -f=diff -f.diff.strip=1 \
              -name="json-suggester" \
              -reporter=github-pr-review \
              -fail-on-error=false < suggestions.diff -tee
          else
            echo "No suggestions.diff file found, skipping reviewdog."
          fi
