name: LanguageTool
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write
jobs:
  grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run LanguageTool API and comment per file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd "$GITHUB_WORKSPACE"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          for file in $(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -E '\.md$|\.mdx$'); do
            echo "Reviewing $file"
            # Fetch LanguageTool results and aggregate all issues for the file
            result=$(curl -s -X POST \
              -d "language=en-US&text=$(awk 'f{print} /^---/{f^=1}' "$file" | jq -s -R -r @uri)" \
              https://api.languagetool.org/v2/check \
            | jq -r --arg f "$file" '
                .matches[]? |
                "- [\($f):\(.offset)] \(.message) — proposed: \(.replacements[].value)"')

            if [ -n "$result" ]; then
              # Truncate if too long for GitHub comment
              max=65000
              if [ ${#result} -gt $max ]; then
                result="${result:0:$max}\n\n...truncated, too many issues to display."
              fi
              gh pr comment ${{ github.event.pull_request.number }} --body "## LanguageTool Report for $file $result"
            fi
          done