name: LanguageTool
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write
jobs:
  grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run LanguageTool API and comment per file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          for file in $(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -E '\.md$|\.txt$'); do
            result=$(curl -s -X POST \
              -d "language=en-US&text=$(jq -s -R -r @uri < $file)" \
              https://api.languagetool.org/v2/check \
            | jq --arg f "$file" '
                .matches[]? |
                "- [\($f):\(.offset)] \(.message) — proposed: \(.replacements[].value)"')
            if [ -n "$result" ]; then
              gh pr comment ${{ github.event.pull_request.number }} --body "## LanguageTool Report for $file\n$result"
            fi
          done