name: LanguageTool
on: pull_request
jobs:
  grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
      - name: Run LanguageTool API and comment per file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -E '\.md$|\.txt$'); do
            result=$(curl -s -X POST \
              -d "language=en-US&text=$(jq -s -R -r @uri < $file)" \
              https://api.languagetool.org/v2/check \
            | jq --arg f "$file" '
                .matches[]? |
                "- [\($f):\(.offset)] \(.message) — proposed: \(.replacements[].value)"')
            if [ -z "$result" ]; then
              result="*No issues found.*"
            fi
            gh pr comment ${{ github.event.pull_request.number }} --body "## LanguageTool Report for $file\n$result"
          done
